### PR TITLE
Fix Profile Photos Not Being Assigned For Ubisoft Accounts

### PR DESCRIPTION
**Pull request by Exhigh**
* Fix the incomplete environment variable that should be replaced.
* Fix the incomplete path used for checking ids and the incorrect function call to clean the path
* Fix the issue with clearing old account images (was using account name rather than id to clear the image)
* Some additional path cleanup and fix the stored order of the users not having the removed user id not removed from the order.

P.S: To fix the profile photo not showing users will need to forget their account and save the account again, to show their profile photo. This behavior could be changed but feedback is necessary.

### CODE REVIEW

**Comment by Exhigh** [comment]
@TCNOco

**Comment by TCNOco** [comment]
Thanks for all of these! I will merge and compile another release soon—probably Monday. A lot of these are simple mistakes I've left in somehow. Thanks a ton!

**Comment by TCNOco** [comment]
Also:
My code signing certificate expired within the last month or so, and even though I got 3 years for ~$200 it would now be closer to $800. I am contacting a company that may be able to help :) Update will be delayed until I have confirmation of a new signing cert.

**Comment by TCNOco** [comment]
Hey, a quick update. I do apologize for the delay. I have since reached out to someone who can help give a signing certificate, which I understand isn't the end of the world if it's not signed - but being a high-trust requiring program it's a good idea to have it signed - and they are happy to help... But the project needs to be built on GitHub Actions or, preferably, AppVeyor.
While simple in theory, I have been struggling to create a build with it. I am actively working on it in my free time here: https://github.com/TCNOco/TcNo-Acc-Switcher/tree/appveyor

Having never used a CI/CD like GitHub Actions or Appveyor, I'm struggling to get it to work properly (There's also a lot being done here in this project than a much simpler codebase built entirely in one project in C#, for example). I should hopefully have this done relatively soon, which should also help me build and release changes more quickly, which would be fantastic. Ther is a lot of work I manually do for releases and having them simplified would be great.

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.

**Pull request merged**
